language: cpp
compiler: gcc g++
sudo: true
# install:
#  - libxrandr
#  - libwrandr
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      libxrandr2
      #libwrandr-dev
    
script:
  - cd build
  - cmake -DBUILD_SHARED_LIBS=OFF ..
  - g++ -v
