language: cpp
compiler: gcc g++
sudo: true
# install:
#  - libxrandr
#  - libwrandr
os: windows
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      libxrandr2
      #libwrandr-dev
    
script:
  - cd build
  - cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=OFF ..
  - make -j
  - g++ -v
